server:
  port: 8082
jasypt:
  encryptor:
    bean: jasyptEncrypt
#spring
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  profiles:
    active: dev

  session:
    store-type: none
  cache:
    type: redis
  mail: #邮件发送
    host: smtp.163.com
    username: test@163.com
    sender: test@163.com
    password: test
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis: #redis 配置
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000
      database: 0

  #DATABASE CONFIG
  datasource:
    #    Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    SqlServer
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    Oracle
    #    driver-class-name: oracle.jdbc.driver.OracleDriver
  web:
    resources:
      static-locations: file:${oss.local.upload-file-path}

#mybatis
mybatis-plus:
  mapper-locations: classpath*:com/sunseagear/wind/modules/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.sunseagear.wind.modules.*.entity
  global-config:
    db-config:
      #主键类型 com.baomidou.mybatisplus.annotation.IdType";
      id-type: ASSIGN_ID
      #字段策略 com.baomidou.mybatisplus.annotation.FieldStrategy"
      where-strategy: NOT_EMPTY
      insert-strategy: NOT_EMPTY
      update-strategy: IGNORED
      #逻辑删除配置（下面3个配置）
      #删除值
      logic-delete-value: 1
      #不删除值
      logic-not-delete-value: 0
      # 逻辑删除字段
      logic-delete-field: del_flag
  configuration:
    jdbc-type-for-null: 'null'
    #数据库大写下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
    #开启sql日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  configuration-properties:
    #设置全局属性用于控制数据库的类型
    dbType: mysql

#  logging
logging:
  config: classpath:log/logback-${spring.profiles.active}.xml

#beetl配置
beetlsql:
  enabled: false


#文件上传配置
#使用的上传存储空间,local本地,aliyun:阿里云,tencent:腾讯,qiniu:七牛云
oss:
  client-type: local
  #默认上传目录
  base_dir: userfiles
  #允许的文件扩展名
  allowed_extension: mp4,bmp, gif, jpg, jpeg, png,doc, docx, xls, xlsx, ppt, pptx,html,htm,txt,rar, zip, gz, bz2,pdf
  #最大文件大小 50M
  max_size: 52428800
  #是否需要按照日期存放文件
  needDatePath: false
  #是否保留原有文件名
  originalName: true

  local:
    domain: http://localhost:8082
    upload-file-path: D:/sunseagear
  aliyun:
    #阿里云api的内或外网域名
    endpoint: oss-cn-beijing.aliyuncs.com
    #阿里云api的密钥access key id
    access-key-id:
    #阿里云api的密钥access key secret
    access-key-secret:
    #阿里云api的bucket名称
    bucket-name:
    #外部访问域名
    domain: http://xxxxx.oss-cn-beijing.aliyuncs.com
  tencent:
    #腾讯云api密钥secretId
    secret-id:
    #腾讯云api密钥secretKey
    secret-key:
    #腾讯云api存储桶所属地域
    region:
    #腾讯云api存储桶空间名称
    bucket-name:
    #腾讯云api存储桶访问域名
    domain:
    #腾讯云api上传文件前缀路径(eg:images/) 设置自己的主目录
    prefix:
  qiniu:
    #七牛云密钥accessKey
    access-key:
    #七牛云密钥secretKey
    secret-key:
    #七牛云存储桶空间名称
    bucket-name:
    #七牛云存储桶访问域名
    domain:
    #七牛云存储桶上传文件前缀路径(eg:images/) 设置自己的主目录
    prefix:


#短信配置
sms:
  #短信配置 aliyun,tencent,huyi
  client-type: tencent
  open: true
  sign-name: 飞廉
  aliyun:
    #阿里云api的密钥access key id
    access-key-id: 阿里云ID
    #阿里云api的密钥access key secret
    access-key-secret: 阿里云 key
  #腾讯云
  tencent:
    #在腾讯云控制台 短信-应用管理里面
    app-id:
    app-key:
    #在腾讯云控制台 个人中心-访客管理的授权用户的id 和key
    SecretId:
    SecretKey:
  huyi:
    #互易api的密钥app id
    account-api-id: 互易ID
    #互易的密钥ap key
    account-api-key: 互易 key

#定时任务配置
quartz:
  open-cluster: false # 是否开启集群
  config-location: /quartz/quartz.properties # 集群配置文件路径
  data-source: qzDS # 集群数据库，使用当前数据库可以设置为空或者default

