#spring
spring:
  mail: #邮件发送
    host: smtp.exmail.qq.com
    username: liangwei@sunseagear.com
    sender: liangwei@sunseagear.com
    password: 您的密码
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis: #redis 配置
      host: 172.18.0.3
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000
      database: 3

  #DATABASE CONFIG
  datasource:
    username: appdev
    password: ENC(86D2CF4AF1DEDE07431A8EB2B28E8EBDEACF08AF3D75ABF03F86BF60CBC6FBCE6168F54A2135E7583A6E7F2F1CFC1AB9FF1711E5F83E2F3AC29D597C7126699258D7FD03DA63F592029B416F3BEBD0F332093824863B9008CC1466A3A561A4FE9C2BA1ECE2F1ABCCCC090DB6DF9233715E349A168BB947D7C8D1EFD071EC1C83)
    url: jdbc:mysql://rm-2zej6285404z242zao.mysql.rds.aliyuncs.com:3306/wind_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai


#文件上传配置
#使用的上传存储空间,local本地,aliyun:阿里云
oss:

  local:
    #文件域名
    domain: http://localhost:8080
    #存储路径
    upload-file-path: D:/wind
  aliyun:
    #阿里云api的内或外网域名
    endpoint: oss-cn-beijing.aliyuncs.com
    #阿里云api的密钥access key id
    access-key-id:
    #阿里云api的密钥access key secret
    access-key-secret:
    #阿里云api的bucket名称
    bucket-name:
    #外部访问域名
    domain: http://xxxxx.oss-cn-beijing.aliyuncs.com
  tencent:
    #腾讯云api密钥secretId
    secret-id:
    #腾讯云api密钥secretKey
    secret-key:
    #腾讯云api存储桶所属地域
    region:
    #腾讯云api存储桶空间名称
    bucket-name:
    #腾讯云api存储桶访问域名
    domain:
    #腾讯云api上传文件前缀路径(eg:images/) 设置自己的主目录
    prefix:
  qiniu:
    #七牛云密钥accessKey
    access-key:
    #七牛云密钥secretKey
    secret-key:
    #七牛云存储桶空间名称
    bucket-name:
    #七牛云存储桶访问域名
    domain:
    #七牛云存储桶上传文件前缀路径(eg:images/) 设置自己的主目录
    prefix:


