#spring
spring:
  mail: #邮件发送
    host: smtp.163.com
    username: test@163.com
    sender: test@163.com
    password: test
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis: #redis 配置
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000
      database: 0

  #DATABASE CONFIG
  datasource:
    username: root
    password: 123456
    # 密码加密方法详见JasyptEncrypt类
    # password: ENC(5292127E56E64C2A6DE049773E7D48CB5783F956D7C0FC1648578C18A8C5C191FCA907A5E3EF1C606F0CFEB76F9E9FA24A85378AF38053801613EDE4121536771413DF89519CD24289F816B011BDA2DBAAA2C1C1635CF55E3B8227751BCAADAA41ABBE93B7A54A94ECAE967E1EE8CDFD7FCCD30F852B6F0DA9406706949647C5)
    url: jdbc:mysql://localhost:3306/wind?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

#文件上传配置
#使用的上传存储空间,local本地,aliyun:阿里云
oss:

  local:
    #文件域名
    domain: http://localhost:8080
    #存储路径
    upload-file-path: D:/wind
  aliyun:
    #阿里云api的内或外网域名
    endpoint: oss-cn-beijing.aliyuncs.com
    #阿里云api的密钥access key id
    access-key-id:
    #阿里云api的密钥access key secret
    access-key-secret:
    #阿里云api的bucket名称
    bucket-name:
    #外部访问域名
    domain: http://xxxxx.oss-cn-beijing.aliyuncs.com
  tencent:
    #腾讯云api密钥secretId
    secret-id:
    #腾讯云api密钥secretKey
    secret-key:
    #腾讯云api存储桶所属地域
    region:
    #腾讯云api存储桶空间名称
    bucket-name:
    #腾讯云api存储桶访问域名
    domain:
    #腾讯云api上传文件前缀路径(eg:images/) 设置自己的主目录
    prefix:
  qiniu:
    #七牛云密钥accessKey
    access-key:
    #七牛云密钥secretKey
    secret-key:
    #七牛云存储桶空间名称
    bucket-name:
    #七牛云存储桶访问域名
    domain:
    #七牛云存储桶上传文件前缀路径(eg:images/) 设置自己的主目录
    prefix:


#短信配置
sms:
  client-type: aliyun
  open: true
  sign-name:
  aliyun:
    #阿里云api的密钥access key id
    access-key-id: 阿里云ID
    #阿里云api的密钥access key secret
    access-key-secret: 阿里云 key

